import type { AssetEntryInput, AssetManifestV2, AssetProductionStandards } from './Types';
import { ASSET_MANIFEST_VERSION } from './Types';

export const ASSET_PRODUCTION_STANDARDS: AssetProductionStandards = {
  space: {
    projection: 'isometric-2:1',
    sourceTileWidth: 128,
    sourceTileHeight: 64,
    worldUnitsPerTile: 28,
    unitReferenceHeight: 24,
  },
  animation: {
    directions: ['NE', 'SE', 'SW', 'NW'],
    coreStates: ['idle', 'walk', 'attack', 'hit', 'death'],
    civilianStates: ['gather', 'carry-resource', 'build'],
    rangedStates: ['attack-anticipation', 'projectile-release'],
    casterStates: ['cast', 'channel'],
  },
  atlas: {
    padding: 2,
    spacing: 2,
    powerOfTwo: true,
    maxSize: 4096,
  },
  teamColor: {
    requiredForFactionAssets: true,
    channel: 'red',
    mode: 'replace',
  },
};

/** Shorthand for authoring; omitted fields get category defaults. */
function a(entry: AssetEntryInput): AssetEntryInput {
  return entry;
}

/**
 * Manifest v2 data for current art kit.
 * Scales / pivots match existing SpriteMap + draw call behavior so rendering stays stable.
 */
export const ASSET_MANIFEST_V2: AssetManifestV2 = {
  version: ASSET_MANIFEST_VERSION,
  standards: ASSET_PRODUCTION_STANDARDS,
  assets: [
    // —— Humans buildings ——
    a({
      id: 'human/town-hall',
      category: 'building',
      src: '/assets/humans/buildings/town-hall.png',
      faction: 'humans',
      role: 'main',
      worldScale: 0.3,
      footprint: { width: 100, height: 100 },
      footprintTiles: { columns: 4, rows: 4 },
      collisionFootprint: { width: 90, height: 90 },
      selectionRadius: 56,
      blocksMovement: true,
      blocksVision: true,
      tags: ['building', 'main', 'humans'],
    }),
    a({
      id: 'human/barracks',
      category: 'building',
      src: '/assets/humans/buildings/barracks.png',
      faction: 'humans',
      role: 'production',
      worldScale: 0.26,
      footprint: { width: 80, height: 80 },
      footprintTiles: { columns: 3, rows: 2 },
      collisionFootprint: { width: 72, height: 72 },
      selectionRadius: 48,
      tags: ['building', 'production', 'humans'],
    }),
    a({
      id: 'human/farm',
      category: 'building',
      src: '/assets/humans/buildings/farm.png',
      faction: 'humans',
      role: 'economy',
      worldScale: 0.22,
      footprint: { width: 60, height: 60 },
      footprintTiles: { columns: 2, rows: 2 },
      collisionFootprint: { width: 54, height: 54 },
      selectionRadius: 36,
      tags: ['building', 'economy', 'humans'],
    }),
    a({
      id: 'human/watchtower',
      category: 'building',
      src: '/assets/humans/buildings/watchtower.png',
      faction: 'humans',
      role: 'defense',
      worldScale: 0.24,
      footprint: { width: 50, height: 50 },
      footprintTiles: { columns: 1, rows: 1 },
      collisionFootprint: { width: 44, height: 44 },
      selectionRadius: 32,
      tags: ['building', 'defense', 'humans', 'unused-in-gameplay'],
    }),
    a({
      id: 'human/outpost',
      category: 'building',
      src: '/assets/world/human-outpost.png',
      faction: 'humans',
      role: 'outpost',
      worldScale: 0.34,
      footprint: { width: 50, height: 50 },
      footprintTiles: { columns: 1, rows: 1 },
      collisionFootprint: { width: 44, height: 44 },
      selectionRadius: 32,
      productionStatus: 'prototype',
      tags: ['building', 'outpost', 'humans', 'living-world-v2'],
    }),

    // —— Humans units ——
    a({
      id: 'human/worker',
      category: 'unit',
      src: '/assets/humans/units/worker.png',
      faction: 'humans',
      role: 'worker',
      worldScale: 0.22,
      selectionRadius: 16,
      tags: ['unit', 'worker', 'humans'],
    }),
    a({
      id: 'human/swordsman',
      category: 'unit',
      src: '/assets/humans/units/swordsman.png',
      faction: 'humans',
      role: 'melee',
      worldScale: 0.24,
      tags: ['unit', 'melee', 'humans'],
    }),
    a({
      id: 'human/archer',
      category: 'unit',
      src: '/assets/humans/units/archer.png',
      faction: 'humans',
      role: 'ranged',
      worldScale: 0.23,
      tags: ['unit', 'ranged', 'humans'],
    }),
    a({
      id: 'human/mage',
      category: 'unit',
      src: '/assets/humans/units/mage.png',
      faction: 'humans',
      role: 'caster',
      worldScale: 0.24,
      tags: ['unit', 'caster', 'humans', 'unused-in-gameplay'],
    }),

    // —— Orcs buildings ——
    a({
      id: 'orc/stronghold',
      category: 'building',
      src: '/assets/orcs/buildings/stronghold.png',
      faction: 'orcs',
      role: 'main',
      worldScale: 0.26,
      footprint: { width: 100, height: 100 },
      footprintTiles: { columns: 4, rows: 4 },
      collisionFootprint: { width: 90, height: 90 },
      selectionRadius: 56,
      tags: ['building', 'main', 'orcs'],
    }),
    a({
      id: 'orc/barracks',
      category: 'building',
      src: '/assets/orcs/buildings/barracks.png',
      faction: 'orcs',
      role: 'production',
      worldScale: 0.24,
      footprint: { width: 80, height: 80 },
      footprintTiles: { columns: 3, rows: 2 },
      collisionFootprint: { width: 72, height: 72 },
      selectionRadius: 48,
      tags: ['building', 'production', 'orcs'],
    }),
    a({
      id: 'orc/war-hut',
      category: 'building',
      src: '/assets/orcs/buildings/war-hut.png',
      faction: 'orcs',
      role: 'economy',
      worldScale: 0.2,
      footprint: { width: 60, height: 60 },
      footprintTiles: { columns: 2, rows: 2 },
      collisionFootprint: { width: 54, height: 54 },
      selectionRadius: 36,
      tags: ['building', 'economy', 'orcs'],
    }),
    a({
      id: 'orc/spike-tower',
      category: 'building',
      src: '/assets/orcs/buildings/spike-tower.png',
      faction: 'orcs',
      role: 'defense',
      worldScale: 0.24,
      footprint: { width: 50, height: 50 },
      footprintTiles: { columns: 1, rows: 1 },
      collisionFootprint: { width: 44, height: 44 },
      selectionRadius: 32,
      tags: ['building', 'defense', 'orcs', 'unused-in-gameplay'],
    }),
    a({
      id: 'orc/outpost',
      category: 'building',
      src: '/assets/world/orc-outpost.png',
      faction: 'orcs',
      role: 'outpost',
      worldScale: 0.32,
      footprint: { width: 50, height: 50 },
      footprintTiles: { columns: 1, rows: 1 },
      collisionFootprint: { width: 44, height: 44 },
      selectionRadius: 32,
      productionStatus: 'prototype',
      tags: ['building', 'outpost', 'orcs', 'living-world-v2'],
    }),

    // —— Orcs units ——
    a({
      id: 'orc/peon',
      category: 'unit',
      src: '/assets/orcs/units/peon.png',
      faction: 'orcs',
      role: 'worker',
      worldScale: 0.22,
      selectionRadius: 16,
      tags: ['unit', 'worker', 'orcs'],
    }),
    a({
      id: 'orc/grunt',
      category: 'unit',
      src: '/assets/orcs/units/grunt.png',
      faction: 'orcs',
      role: 'melee',
      worldScale: 0.2,
      tags: ['unit', 'melee', 'orcs'],
    }),
    a({
      id: 'orc/spear-orc',
      category: 'unit',
      src: '/assets/orcs/units/spear-orc.png',
      faction: 'orcs',
      role: 'ranged',
      worldScale: 0.22,
      tags: ['unit', 'ranged', 'orcs'],
    }),
    a({
      id: 'orc/shaman',
      category: 'unit',
      src: '/assets/orcs/units/shaman.png',
      faction: 'orcs',
      role: 'caster',
      worldScale: 0.24,
      tags: ['unit', 'caster', 'orcs', 'unused-in-gameplay'],
    }),

    // —— Terrain tiles ——
    a({
      id: 'terrain/grass',
      category: 'terrain',
      src: '/assets/terrain/grass.png',
      role: 'ground',
      terrainType: 'grass',
      walkable: true,
      movementCost: 1,
      elevationType: 'flat',
      defenseModifier: 0,
      visionModifier: 1,
      tags: ['terrain', 'ground'],
    }),
    a({
      id: 'terrain/dirt',
      category: 'terrain',
      src: '/assets/terrain/dirt.png',
      role: 'ground',
      terrainType: 'hill',
      walkable: true,
      movementCost: 1.15,
      elevationType: 'raised',
      defenseModifier: 0,
      visionModifier: 1.15,
      tags: ['terrain', 'hill'],
    }),
    a({
      id: 'terrain/rocks',
      category: 'terrain',
      src: '/assets/terrain/rocks.png',
      role: 'ground',
      terrainType: 'mountain',
      walkable: false,
      movementCost: null,
      elevationType: 'high',
      defenseModifier: 0,
      visionModifier: 0.5,
      blocksMovement: true,
      blocksVision: true,
      tags: ['terrain', 'mountain'],
    }),
    a({
      id: 'terrain/water',
      category: 'terrain',
      src: '/assets/terrain/water.png',
      role: 'water',
      terrainType: 'river',
      walkable: false,
      movementCost: null,
      elevationType: 'water',
      defenseModifier: 0,
      visionModifier: 1,
      blocksMovement: true,
      riverConnectionMask: 15,
      tags: ['terrain', 'water', 'river'],
    }),
    a({
      id: 'terrain/path-straight',
      category: 'terrain',
      src: '/assets/terrain/path-straight.png',
      role: 'road',
      terrainType: 'road',
      walkable: true,
      movementCost: 1 / 1.15,
      elevationType: 'flat',
      roadConnectionMask: 5,
      tags: ['terrain', 'road'],
    }),
    a({
      id: 'terrain/path-corner',
      category: 'terrain',
      src: '/assets/terrain/path-corner.png',
      role: 'road',
      terrainType: 'road',
      walkable: true,
      movementCost: 1 / 1.15,
      elevationType: 'flat',
      roadConnectionMask: 3,
      tags: ['terrain', 'road', 'variant'],
    }),
    a({
      id: 'terrain/path-cross',
      category: 'terrain',
      src: '/assets/terrain/path-cross.png',
      role: 'road',
      terrainType: 'road',
      walkable: true,
      movementCost: 1 / 1.15,
      elevationType: 'flat',
      roadConnectionMask: 15,
      tags: ['terrain', 'road', 'variant'],
    }),
    a({
      id: 'terrain/path-t-junction',
      category: 'terrain',
      src: '/assets/terrain/path-t-junction.png',
      role: 'road',
      terrainType: 'road',
      walkable: true,
      movementCost: 1 / 1.15,
      elevationType: 'flat',
      roadConnectionMask: 7,
      tags: ['terrain', 'road', 'variant'],
    }),
    a({
      id: 'terrain/shore-straight',
      category: 'terrain',
      src: '/assets/terrain/shore-straight.png',
      role: 'shore',
      terrainType: 'river',
      walkable: false,
      elevationType: 'water',
      riverConnectionMask: 1,
      tags: ['terrain', 'shore', 'variant'],
    }),
    a({
      id: 'terrain/shore-inner-corner',
      category: 'terrain',
      src: '/assets/terrain/shore-inner-corner.png',
      role: 'shore',
      terrainType: 'river',
      walkable: false,
      elevationType: 'water',
      riverConnectionMask: 3,
      tags: ['terrain', 'shore', 'inner-corner', 'variant'],
    }),
    a({
      id: 'terrain/shore-outer-corner',
      category: 'terrain',
      src: '/assets/terrain/shore-outer-corner.png',
      role: 'shore',
      terrainType: 'river',
      walkable: false,
      elevationType: 'water',
      riverConnectionMask: 3,
      tags: ['terrain', 'shore', 'outer-corner', 'variant'],
    }),
    a({
      id: 'world/hill',
      category: 'terrain',
      src: '/assets/world/hill.png',
      role: 'ground',
      terrainType: 'hill',
      walkable: true,
      movementCost: 1.15,
      elevationType: 'raised',
      visionModifier: 1.15,
      tags: ['terrain', 'hill', 'living-world-v2'],
    }),
    a({
      id: 'world/bridge',
      category: 'terrain',
      src: '/assets/world/bridge.png',
      role: 'bridge',
      terrainType: 'bridge',
      walkable: true,
      movementCost: 1,
      elevationType: 'flat',
      roadConnectionMask: 5,
      tags: ['terrain', 'bridge', 'chokepoint', 'living-world-v2'],
    }),

    // —— Decorations / props ——
    a({
      id: 'terrain/tree-deciduous',
      category: 'decoration',
      src: '/assets/terrain/tree-deciduous.png',
      role: 'tree',
      worldScale: 0.28,
      blocksVision: true,
      tags: ['decoration', 'tree'],
    }),
    a({
      id: 'terrain/tree-pine',
      category: 'decoration',
      src: '/assets/terrain/tree-pine.png',
      role: 'tree',
      worldScale: 0.28,
      blocksVision: true,
      tags: ['decoration', 'tree', 'pine'],
    }),
    a({
      id: 'terrain/stump',
      category: 'decoration',
      src: '/assets/terrain/stump.png',
      role: 'prop',
      worldScale: 0.22,
      tags: ['decoration', 'stump'],
    }),
    a({
      id: 'terrain/bush',
      category: 'decoration',
      src: '/assets/terrain/bush.png',
      role: 'prop',
      worldScale: 0.22,
      tags: ['decoration', 'bush'],
    }),
    a({
      id: 'terrain/flowers',
      category: 'decoration',
      src: '/assets/terrain/flowers.png',
      role: 'prop',
      worldScale: 0.18,
      tags: ['decoration', 'flowers'],
    }),
    a({
      id: 'terrain/blue-flowers',
      category: 'decoration',
      src: '/assets/terrain/blue-flowers.png',
      role: 'prop',
      worldScale: 0.18,
      tags: ['decoration', 'flowers', 'blue'],
    }),
    a({
      id: 'terrain/pebbles',
      category: 'decoration',
      src: '/assets/terrain/pebbles.png',
      role: 'prop',
      worldScale: 0.18,
      tags: ['decoration', 'pebbles'],
    }),
    a({
      id: 'terrain/battlefield-skull',
      category: 'decoration',
      src: '/assets/terrain/battlefield-skull.png',
      role: 'prop',
      worldScale: 0.22,
      tags: ['decoration', 'skull'],
    }),
    a({
      id: 'terrain/cart',
      category: 'decoration',
      src: '/assets/terrain/cart.png',
      role: 'living-city-prop',
      worldScale: 0.24,
      tags: ['decoration', 'cart', 'living-world-v2'],
    }),
    a({
      id: 'terrain/fence',
      category: 'decoration',
      src: '/assets/terrain/fence.png',
      role: 'living-city-prop',
      worldScale: 0.2,
      tags: ['decoration', 'fence', 'living-world-v2'],
    }),
    a({
      id: 'terrain/market-stall',
      category: 'decoration',
      src: '/assets/terrain/market-stall.png',
      role: 'living-city-prop',
      worldScale: 0.22,
      tags: ['decoration', 'market', 'living-world-v2'],
    }),
    a({
      id: 'world/outpost-foundation',
      category: 'building',
      src: '/assets/world/outpost-foundation.png',
      faction: 'neutral',
      role: 'construction-state',
      worldScale: 0.34,
      footprint: { width: 50, height: 50 },
      footprintTiles: { columns: 1, rows: 1 },
      collisionFootprint: { width: 44, height: 44 },
      selectionRadius: 32,
      productionStatus: 'prototype',
      tags: ['building', 'outpost', 'construction', 'living-world-v2'],
    }),

    // —— Resource ——
    a({
      id: 'terrain/gold-deposit',
      category: 'resource',
      src: '/assets/terrain/gold-deposit.png',
      role: 'gold',
      worldScale: 0.32,
      footprintTiles: { columns: 2, rows: 2 },
      pivotY: 0.82,
      selectionRadius: 28,
      blocksMovement: true,
      tags: ['resource', 'gold'],
    }),

    // —— UI ——
    a({ id: 'ui/gold', category: 'ui', src: '/assets/ui/gold.png', role: 'icon', tags: ['ui', 'gold'] }),
    a({
      id: 'ui/population',
      category: 'ui',
      src: '/assets/ui/population.png',
      role: 'icon',
      tags: ['ui', 'population'],
    }),
    a({ id: 'ui/attack', category: 'ui', src: '/assets/ui/attack.png', role: 'icon', tags: ['ui'] }),
    a({ id: 'ui/build', category: 'ui', src: '/assets/ui/build.png', role: 'icon', tags: ['ui'] }),
    a({ id: 'ui/gather', category: 'ui', src: '/assets/ui/gather.png', role: 'icon', tags: ['ui'] }),
    a({ id: 'ui/select', category: 'ui', src: '/assets/ui/select.png', role: 'icon', tags: ['ui'] }),
    a({ id: 'ui/armor', category: 'ui', src: '/assets/ui/armor.png', role: 'icon', tags: ['ui'] }),
    a({ id: 'ui/food', category: 'ui', src: '/assets/ui/food.png', role: 'icon', tags: ['ui'] }),
    a({ id: 'ui/lumber', category: 'ui', src: '/assets/ui/lumber.png', role: 'icon', tags: ['ui'] }),
    a({ id: 'ui/speed', category: 'ui', src: '/assets/ui/speed.png', role: 'icon', tags: ['ui'] }),
    a({
      id: 'ui/enemy-alert',
      category: 'ui',
      src: '/assets/ui/enemy-alert.png',
      role: 'icon',
      tags: ['ui'],
    }),
    a({
      id: 'ui/crossed-swords',
      category: 'ui',
      src: '/assets/ui/crossed-swords.png',
      role: 'icon',
      tags: ['ui'],
    }),

    // —— VFX ——
    a({
      id: 'vfx/hit-spark',
      category: 'vfx',
      src: '/assets/vfx/hit-spark.png',
      role: 'hit',
      worldScale: 0.18,
      tags: ['vfx', 'combat'],
    }),
    a({
      id: 'vfx/impact-flash',
      category: 'vfx',
      src: '/assets/vfx/impact-flash.png',
      role: 'hit',
      tags: ['vfx'],
    }),
    a({
      id: 'vfx/dust-puff',
      category: 'vfx',
      src: '/assets/vfx/dust-puff.png',
      role: 'ambient',
      tags: ['vfx'],
    }),
    a({
      id: 'vfx/damage-slash',
      category: 'vfx',
      src: '/assets/vfx/damage-slash.png',
      role: 'hit',
      tags: ['vfx', 'combat'],
    }),
    a({
      id: 'vfx/arrow-projectile',
      category: 'vfx',
      src: '/assets/vfx/arrow-projectile.png',
      role: 'projectile',
      tags: ['vfx', 'projectile'],
    }),
    a({
      id: 'vfx/death-wisp',
      category: 'vfx',
      src: '/assets/vfx/death-wisp.png',
      role: 'death',
      tags: ['vfx'],
    }),
    a({
      id: 'vfx/healing-burst',
      category: 'vfx',
      src: '/assets/vfx/healing-burst.png',
      role: 'healing',
      tags: ['vfx', 'healing'],
    }),
    a({
      id: 'vfx/magic-burst',
      category: 'vfx',
      src: '/assets/vfx/magic-burst.png',
      role: 'magic',
      tags: ['vfx', 'magic'],
    }),
  ],
};
